export type ExamType = 'JEE_MAINS' | 'JEE_ADVANCED' | 'NEET';
export type SubjectType = 'Physics' | 'Chemistry' | 'Mathematics' | 'Biology';
export type PublisherType = 'NCERT' | 'Cengage' | 'Arihant' | 'Allen' | 'PW' | 'Unacademy';
export type ClassLevel = 11 | 12;

export interface CurriculumTopic {
  name: string;
  description?: string;
}

export interface CurriculumChapter {
  name: string;
  number: number;
  classLevel: ClassLevel;
  topics: CurriculumTopic[];
  description?: string;
}

export interface Provenance {
  source: string; // e.g., 'Cengage', 'NCERT', 'synthesized'
  edition?: string; // optional edition or year
  url?: string; // optional link to TOC or publisher page
  notes?: string; // any freeform notes about mapping decisions
  version?: string; // mapping/version identifier
  timestamp?: string; // ISO timestamp when this mapping was created/annotated
}

// local types that carry optional provenance
export type CurriculumTopicWithProv = CurriculumTopic;
export type CurriculumChapterWithProv = CurriculumChapter;
export type CurriculumDataWithProv = CurriculumData;

export interface CurriculumData {
  publisher: PublisherType;
  exam: ExamType;
  subject: SubjectType;
  chapters: CurriculumChapter[];
}

const topicList = (...topics: string[]): CurriculumTopic[] => topics.map((name) => ({ name }));

const chapter = (
  number: number,
  classLevel: ClassLevel,
  name: string,
  topics: string[],
  description?: string,
): CurriculumChapter => ({
  number,
  classLevel,
  name,
  topics: topicList(...topics),
  description,
});

const physicsClass11: CurriculumChapter[] = [
  chapter(1, 11, 'Units and Measurements', [
    'Physical quantities and SI units',
    'Fundamental units and derived units',
    'CGS and MKS systems',
    'Dimensions of physical quantities',
    'Dimensional analysis and applications',
    'Dimensional consistency and equations',
    'Significant figures and rounding off',
    'Scientific notation and order of magnitude',
    'Errors in measurement: systematic and random',
    'Absolute, relative and percentage errors',
    'Combination of errors in calculations',
    'Precision, accuracy and measurement uncertainty',
    'Vernier caliper and screw gauge',
  ]),
  chapter(2, 11, 'Motion in a Straight Line', [
    'Position vector and displacement',
    'Speed versus velocity',
    'Average velocity and instantaneous velocity',
    'Acceleration and retardation',
    'Equations of uniformly accelerated motion',
    'Graphical analysis of motion',
    'Graphs of position-time, velocity-time, acceleration-time',
    'Interpretation of slopes and areas under curves',
    'Free fall motion and motion under gravity',
    'Motion in vertical direction',
    'Relative velocity in one dimension',
    'Stopping distance and reaction time',
  ]),
  chapter(3, 11, 'Motion in a Plane', [
    'Scalars and vectors',
    'Vector representation and notation',
    'Addition and subtraction of vectors',
    'Components of vectors and resolution',
    'Dot product and cross product',
    'Relative velocity in two dimensions',
    'Reference frames and frame transformation',
    'Projectile motion and trajectory',
    'Range, time of flight and maximum height',
    'Angle of projection and range relationship',
    'Uniform circular motion',
    'Angular velocity and angular acceleration',
    'Centripetal acceleration and force',
    'Period and frequency in circular motion',
    'Conical pendulum applications',
  ]),
  chapter(4, 11, 'Laws of Motion', [
    'Newton first law and inertia',
    'Newton second law and force',
    'Newton third law and action-reaction',
    'Momentum and change in momentum',
    'Impulse-momentum theorem',
    'Free body diagrams and force analysis',
    'Equilibrium conditions and static equilibrium',
    'Types of friction: static, kinetic, rolling',
    'Coefficient of friction and limiting friction',
    'Tension and normal force calculations',
    'Circular motion dynamics',
    'Dynamics of circular motion in vertical plane',
    'Connected bodies and pulley systems',
    'Motion on inclined planes',
    'Banking of roads and curves',
    'Applications to real-world scenarios',
  ]),
  chapter(5, 11, 'Work, Energy and Power', [
    'Work done by constant force',
    'Work done by variable force',
    'Work-energy theorem and proof',
    'Kinetic energy and its relationship to work',
    'Potential energy and conservative forces',
    'Conservative and non-conservative forces',
    'Gravitational potential energy',
    'Elastic potential energy and spring force',
    'Conservation of mechanical energy',
    'Energy conservation with friction and drag',
    'Power and its definition',
    'Average power and instantaneous power',
    'Efficiency and energy loss',
    'Elastic and inelastic collisions',
    'Collision in one and two dimensions',
    'Coefficient of restitution',
  ]),
  chapter(6, 11, 'System of Particles and Rotational Motion', [
    'Centre of mass concept and location',
    'Centre of gravity and centre of mass',
    'Linear momentum of system of particles',
    'Conservation of momentum',
    'Torque and moment of force',
    'Angular momentum and rotational motion',
    'Moment of inertia and mass distribution',
    'Parallel axis theorem and perpendicular axis theorem',
    'Radius of gyration',
    'Rolling motion without slipping',
    'Rotational kinetic energy',
    'Kinetic energy in rolling motion',
    'Angular acceleration and equation of motion',
    'Equilibrium of rigid bodies',
    'Rotational equilibrium conditions',
    'Couple and its effects',
  ]),
  chapter(7, 11, 'Gravitation', [
    'Universal law of gravitation and Newton',
    'Gravitational field strength and intensity',
    'Gravitational potential and potential energy',
    'Conservative nature of gravitational force',
    'Acceleration due to gravity at different altitudes',
    'Variation of g with latitude and rotation',
    'Gravitational field inside and outside spheres',
    'Motion of satellites and orbital mechanics',
    'Orbital velocity and escape velocity',
    'Geostationary satellites',
    'Kepler laws of planetary motion',
    'Binary star systems and reduced mass',
    'Black holes and gravitational collapse',
    'Weightlessness and apparent weight',
  ]),
  chapter(8, 11, 'Mechanical Properties of Solids', [
    'Elastic and plastic deformation',
    'Stress: tensile, compressive, shear',
    'Strain: longitudinal, volumetric, shear',
    'Hooke law and elastic limit',
    'Young modulus and measurement',
    'Bulk modulus and compressibility',
    'Shear modulus and rigidity',
    'Poisson ratio and material properties',
    'Stress-strain curve and failure',
    'Elastic energy stored and resilience',
    'Ductility and brittleness',
    'Fatigue and creep in materials',
    'Applications to engineering structures',
  ]),
  chapter(9, 11, 'Mechanical Properties of Fluids', [
    'Pressure in fluids at depth',
    'Pressure transmission in fluids',
    'Pascal law and hydraulic devices',
    'Buoyancy and Archimedes principle',
    'Floating and sinking conditions',
    'Density and relative density',
    'Viscosity and Newton law of viscosity',
    'Stokes law and terminal velocity',
    'Streamline and turbulent flow',
    'Continuity equation and mass conservation',
    'Bernoulli principle and equation',
    'Surface tension and surface energy',
    'Contact angle and capillarity',
    'Rise and fall in capillary tubes',
    'Excess pressure in drops and bubbles',
  ]),
  chapter(10, 11, 'Thermal Properties of Matter', [
    'Temperature scales and conversions',
    'Thermal equilibrium and zeroth law',
    'Heat and internal energy',
    'Transfer of heat: conduction, convection, radiation',
    'Thermal conductivity and coefficient',
    'Heat capacity and specific heat capacity',
    'Calorimetry and heat balance',
    'Thermal expansion of solids',
    'Linear and volumetric expansion coefficients',
    'Thermal expansion of liquids and gases',
    'Anomalous expansion of water',
    'Latent heat and phase changes',
    'Melting, freezing, vaporization and condensation',
    'Sublimation and deposition',
    'Cooling curves and phase diagrams',
  ]),
  chapter(11, 11, 'Thermodynamics', [
    'Thermodynamic systems and boundaries',
    'Internal energy and first law formulation',
    'Work done by and on a system',
    'Heat transfer and sign convention',
    'First law of thermodynamics',
    'Thermodynamic processes: isothermal, isobaric, isochoric',
    'Adiabatic processes and applications',
    'PV diagrams and work representation',
    'Heat engines and efficiency',
    'Carnot engine and maximum efficiency',
    'Refrigerators and coefficient of performance',
    'Entropy and disorder',
    'Second law of thermodynamics',
    'Reversible and irreversible processes',
    'Entropy change calculations',
  ]),
  chapter(12, 11, 'Kinetic Theory', [
    'Molecular nature of matter',
    'Ideal gas equation and derivation',
    'PV = nRT relationship',
    'Dalton law of partial pressures',
    'Kinetic interpretation of temperature',
    'RMS speed, average speed, most probable speed',
    'Maxwell Boltzmann distribution',
    'Degrees of freedom and equipartition theorem',
    'Mean free path and molecular collisions',
    'Viscosity from kinetic theory',
    'Thermal conductivity from molecular theory',
    'Real gases and van der Waals equation',
    'Deviations from ideal behavior',
  ]),
  chapter(13, 11, 'Oscillations', [
    'Simple harmonic motion definition',
    'Kinematics of SHM',
    'Displacement, velocity, acceleration relationships',
    'Angular frequency and time period',
    'Energy in SHM: kinetic and potential',
    'Total mechanical energy conservation in SHM',
    'Graphical representation of SHM',
    'Spring mass system',
    'Vertical spring oscillation',
    'Simple pendulum and approximation',
    'Compound pendulum and moment of inertia',
    'Damped oscillations and decay',
    'Forced oscillations and resonance',
    'Amplitude resonance and power absorption',
    'Phase relationships in driven oscillations',
  ]),
  chapter(14, 11, 'Waves', [
    'Wave motion and propagation',
    'Transverse and longitudinal waves',
    'Wavelength, frequency, period relationship',
    'Wave speed and medium dependence',
    'Equation of a wave',
    'Particle velocity vs wave velocity',
    'Energy in waves and intensity',
    'Superposition principle',
    'Constructive and destructive interference',
    'Standing waves in strings',
    'Modes of vibration and harmonics',
    'Resonance in air columns',
    'Sound waves and acoustic properties',
    'Doppler effect for sound waves',
    'Mach number and shock waves',
  ]),
];

const physicsClass12: CurriculumChapter[] = [
  chapter(1, 12, 'Electric Charges and Fields', [
    'Electric charge: properties and conservation',
    'Coulomb law and superposition principle',
    'Electric field and field intensity',
    'Electric field due to point charge',
    'Electric field due to dipole',
    'Electric field lines and field visualization',
    'Dipole moment and dipole properties',
    'Torque on a dipole in external field',
    'Electric flux and flux calculation',
    'Gauss law and derivation',
    'Applications of Gauss law',
    'Gauss law for conducting sphere and shell',
    'Gauss law for infinite line and plane charges',
    'Electric field near conductor surfaces',
  ]),
  chapter(2, 12, 'Electrostatic Potential and Capacitance', [
    'Electric potential and potential difference',
    'Potential due to point charge',
    'Potential due to system of charges',
    'Potential due to dipole',
    'Equipotential surfaces',
    'Relationship between field and potential',
    'Potential energy of a charge system',
    'Interaction energy and assembly work',
    'Capacitance and capacitor definition',
    'Parallel plate capacitor',
    'Cylindrical capacitor and spherical capacitor',
    'Series and parallel combination of capacitors',
    'Capacitors with dielectrics',
    'Energy stored in capacitor',
    'Energy density in electric field',
  ]),
  chapter(3, 12, 'Current Electricity', [
    'Electric current and current density',
    'Drift velocity and conductivity',
    'Ohm law and its microscopic origin',
    'Resistivity and temperature dependence',
    'Series and parallel resistance combinations',
    'Kirchhoff first law (current law)',
    'Kirchhoff second law (voltage law)',
    'Wheatstone bridge and balancing',
    'Metalbridgebridge experiment',
    'Potentiometer and applications',
    'Comparison of EMF using potentiometer',
    'Comparison of resistances',
    'Electrical power and energy dissipation',
    'Joule heating and heating effect of current',
    'EMF and internal resistance',
    'Terminal voltage and load current',
  ]),
  chapter(4, 12, 'Moving Charges and Magnetism', [
    'Magnetic field and magnetic force',
    'Lorentz force on moving charge',
    'Motion of charged particle in magnetic field',
    'Cyclotron and cyclotron frequency',
    'Velocity selector and magnetic deflection',
    'Magnetic force on current-carrying conductor',
    'Torque on current loop',
    'Galvanometer and galvanometer conversion',
    'Biot-Savart law',
    'Magnetic field due to straight current',
    'Magnetic field due to circular coil',
    'Ampere circuital law',
    'Magnetic field inside and outside solenoid',
    'Magnetic field due to long solenoid',
    'Force between parallel currents',
    'Definition of ampere unit',
  ]),
  chapter(5, 12, 'Magnetism and Matter', [
    'Magnetic dipole moment',
    'Bar magnet properties',
    'Magnetic field of bar magnet',
    'Equivalent solenoid of bar magnet',
    'Magnetic field of earth',
    'Magnetic declination and inclination',
    'Magnetization and magnetic intensity',
    'Susceptibility and permeability',
    'Magnetic materials: paramagnetic, diamagnetic, ferromagnetic',
    'Hysteresis curve',
    'Retentivity and coercivity',
    'Domain theory of magnetization',
    'Curie temperature and material behavior',
  ]),
  chapter(6, 12, 'Electromagnetic Induction', [
    'Magnetic flux and Faraday law',
    'Lenz law and conservation principles',
    'Motional EMF and induced current',
    'EMF in moving rod in magnetic field',
    'Self-inductance and mutual inductance',
    'Self-inductance of solenoid and coil',
    'Energy stored in magnetic field',
    'Energy density in magnetic field',
    'Eddy currents and applications',
    'Eddy current damping',
    'Transformer principle and equation',
    'Ideal and practical transformers',
    'Power transmission and losses',
  ]),
  chapter(7, 12, 'Alternating Current', [
    'AC voltage and AC current',
    'RMS value and peak value',
    'Average value and form factor',
    'AC circuit with pure resistance',
    'AC circuit with pure inductance',
    'AC circuit with pure capacitance',
    'Series RL circuit',
    'Series RC circuit',
    'Series RLC circuit and resonance',
    'Impedance and phase angle',
    'Power factor and active power',
    'Reactive power and apparent power',
    'Power in AC circuits',
    'Resonance frequency',
    'Quality factor and bandwidth',
    'Transformer working and efficiency',
  ]),
  chapter(8, 12, 'Electromagnetic Waves', [
    'Displacement current and Maxwell correction',
    'Maxwell equations',
    'Electromagnetic wave properties',
    'Speed of electromagnetic waves',
    'Spectrum and classification',
    'Transverse nature of electromagnetic waves',
    'Polarization of electromagnetic waves',
    'Radiation pressure',
    'Intensity and energy density',
    'Poynting vector and energy flow',
    'Radio waves and generation',
    'Microwave properties and applications',
    'Infrared radiation and thermal imaging',
    'Visible light spectrum and colors',
    'Ultraviolet radiation and effects',
    'X-ray generation and properties',
    'Gamma rays and applications',
  ]),
  chapter(9, 12, 'Ray Optics and Optical Instruments', [
    'Law of reflection and mirrors',
    'Concave and convex mirrors',
    'Mirror formula and magnification',
    'Real and virtual images',
    'Law of refraction and Snell law',
    'Refractive index and absolute refractive index',
    'Relative refractive index',
    'Total internal reflection',
    'Critical angle calculation',
    'Optical fiber principle',
    'Prism and refraction through prism',
    'Minimum deviation and prism formula',
    'Chromatic aberration and dispersion',
    'Lens types and lens maker formula',
    'Thin lens formula and magnification',
    'Lens combination and power',
    'Optical instruments: microscope, telescope',
    'Magnifying power and resolving power',
  ]),
  chapter(10, 12, 'Wave Optics', [
    'Huygens principle',
    'Wavefronts and wave propagation',
    'Interference and superposition',
    'Young double slit experiment',
    'Fringe width and interference pattern',
    'Path difference and phase difference',
    'Coherence and coherent sources',
    'Division of amplitude and wavefront',
    'Single slit diffraction',
    'Diffraction pattern and minima',
    'Double slit diffraction pattern',
    'Diffraction grating',
    'Resolving power of optical instruments',
    'Rayleigh criterion',
    'Polarization of light',
    'Brewster angle',
    'Malus law and polaroid filters',
  ]),
  chapter(11, 12, 'Dual Nature of Radiation and Matter', [
    'Photoelectric effect and experiments',
    'Einstein photoelectric equation',
    'Stopping potential and work function',
    'Threshold frequency and wavelength',
    'Photoelectric current and intensity',
    'De Broglie hypothesis',
    'De Broglie wavelength calculation',
    'Matter waves and wave-particle duality',
    'Davisson-Germer experiment',
    'Electron diffraction',
    'Compton effect and Compton shift',
    'Momentum and energy relation',
    'Pair production and annihilation',
  ]),
  chapter(12, 12, 'Atoms', [
    'Rutherford nuclear model',
    'Alpha particle scattering',
    'Nuclear charge and atomic number',
    'Bohr model postulates',
    'Bohr radius and energy levels',
    'Energy levels in hydrogen',
    'Hydrogen spectrum',
    'Lyman, Balmer, Paschen series',
    'Rydberg constant and formula',
    'Quantum numbers and energy levels',
    'Atomic spectra',
    'Line spectrum and continuous spectrum',
    'X-ray spectra',
    'Moseley law',
    'Multi-electron atoms and screening',
  ]),
  chapter(13, 12, 'Nuclei', [
    'Nuclear composition and structure',
    'Atomic mass unit and mass defect',
    'Binding energy and stability',
    'Semi-empirical mass formula',
    'Radioactivity and decay modes',
    'Alpha decay and alpha particles',
    'Beta decay (electron emission)',
    'Beta plus decay and positron',
    'Gamma decay',
    'Radioactive decay law and half-life',
    'Mean life and activity',
    'Decay chains and secular equilibrium',
    'Nuclear fission and chain reaction',
    'Critical mass and reactor control',
    'Nuclear fusion and reactor design',
    'Energy release in reactions',
    'Artificial radioactivity',
  ]),
  chapter(14, 12, 'Semiconductor Electronics', [
    'Semiconductors and band theory',
    'Intrinsic and extrinsic semiconductors',
    'Doping and impurities',
    'P-type and N-type semiconductors',
    'P-N junction formation',
    'Junction potential and depletion layer',
    'Forward and reverse bias',
    'Diode characteristics',
    'Diode as rectifier',
    'Zener diode and breakdown',
    'Zener diode as voltage regulator',
    'Transistor types: BJT, FET',
    'Transistor as amplifier',
    'Transistor as switch',
    'Logic gates: AND, OR, NOT, NAND, NOR, XOR',
    'Boolean algebra basics',
    'Digital electronics and binary',
  ]),
  chapter(15, 12, 'Communication Systems', [
    'Need for modulation',
    'Amplitude modulation principle',
    'Frequency modulation basics',
    'Modulation index and sidebands',
    'Bandwidth requirements',
    'Signal transmission and propagation',
    'Electromagnetic wave propagation',
    'Ground wave and sky wave propagation',
    'Space wave propagation',
    'Antenna: types and radiation pattern',
    'Isotropic radiator and gain',
    'Dipole antenna and resonance',
    'Satellite communication',
    'Geostationary satellites',
    'Digital communication basics',
    'Information theory and Shannon theorem',
  ]),
];

const chemistryClass11: CurriculumChapter[] = [
  chapter(1, 11, 'Some Basic Concepts of Chemistry', [
    'Matter and physical properties',
    'Chemical properties and changes',
    'Pure substances and mixtures',
    'Laws of chemical combination',
    'Law of conservation of mass',
    'Law of definite proportions',
    'Law of multiple proportions',
    'Atomic mass and molecular mass',
    'Mole concept and Avogadro number',
    'Molar mass calculations',
    'Stoichiometry and balancing equations',
    'Limiting reagent problems',
    'Percentage yield calculations',
    'Molarity, molality and mole fraction',
    'Normality and equivalent weight',
    'Dilution formula',
  ]),
  chapter(2, 11, 'Structure of Atom', [
    'Discovery of subatomic particles',
    'Cathode ray experiment',
    'Millikan oil drop experiment',
    'Rutherford alpha scattering',
    'Atomic models: Thomson, Rutherford, Bohr',
    'Limitations of Bohr model',
    'Dual nature of matter',
    'De Broglie wavelength',
    'Heisenberg uncertainty principle',
    'Quantum mechanical model',
    'Quantum numbers and orbitals',
    'Principal quantum number (n)',
    'Azimuthal quantum number (l)',
    'Magnetic quantum number (m)',
    'Spin quantum number (s)',
    'Orbital shapes: s, p, d, f',
    'Electron density and radial probability',
  ]),
  chapter(3, 11, 'Classification of Elements and Periodicity', [
    'Modern periodic table',
    'Periodic law and classification',
    'Electron configuration and periodic trends',
    'Atomic radius trends',
    'Ionic radius and isoelectronic series',
    'Ionization enthalpy and first/successive ionization',
    'Electron gain enthalpy and electronegativity',
    'Oxidation numbers and oxidation states',
    'Metallic character and non-metallic character',
    'Diagonal relationships in periodic table',
    'Block classification: s, p, d, f blocks',
    'Period and group properties',
  ]),
  chapter(4, 11, 'Chemical Bonding and Molecular Structure', [
    'Ionic bonding and electronegativity',
    'Covalent bonding and bond types',
    'Coordinate bonding and dative bonds',
    'Lewis structures and dot representations',
    'Formal charge calculations',
    'Octet rule and exceptions',
    'Expanded octet and hypervalent compounds',
    'VSEPR theory and molecular geometry',
    'Hybridization: sp, sp2, sp3, dsp2, dsp3',
    'Molecular orbital theory basics',
    'Hydrogen bonding and types',
    'Dipole moment and molecular polarity',
    'Valence bond theory',
    'Metallic bonding and properties',
  ]),
  chapter(5, 11, 'States of Matter', [
    'Gaseous state and characteristics',
    'Boyle law and its applications',
    'Charles law and temperature relationships',
    'Gay-Lussac law and pressure-temperature',
    'Ideal gas equation derivation',
    'Dalton law of partial pressures',
    'Gas mixtures and mole fractions',
    'Real gases and deviations',
    'Van der Waals equation',
    'Kinetic theory of gases',
    'Molecular speeds: RMS, average, most probable',
    'Kinetic energy and temperature relationship',
    'Liquefaction and critical temperature',
    'Critical constants and liquefaction',
    'Liquid state properties',
    'Surface tension and capillary action',
    'Viscosity of liquids',
    'Solid state basics',
    'Intermolecular forces classifications',
  ]),
  chapter(6, 11, 'Thermodynamics', [
    'System, surroundings and boundary types',
    'Open, closed and isolated systems',
    'Internal energy concept',
    'First law of thermodynamics',
    'Work and heat definitions',
    'Sign conventions in thermodynamics',
    'Enthalpy and enthalpy changes',
    'Exothermic and endothermic reactions',
    'Heat of formation and heat of reaction',
    'Hess law and applications',
    'Enthalpy calculations',
    'Entropy and disorder',
    'Spontaneity and entropy change',
    'Gibbs free energy',
    'Gibbs-Helmholtz equation',
    'Standard states and thermodynamic values',
    'Absolute entropy calculations',
  ]),
  chapter(7, 11, 'Equilibrium', [
    'Dynamic equilibrium concept',
    'Forward and reverse rates',
    'Equilibrium constant expression',
    'Equilibrium constant and concentrations',
    'Homogeneous and heterogeneous equilibria',
    'Calculating equilibrium constant',
    'Relationship between Kp and Kc',
    'Le Chatelier principle',
    'Effect of concentration changes',
    'Effect of pressure changes',
    'Effect of temperature changes',
    'Effect of catalysts',
    'Ionic equilibrium and weak acids/bases',
    'Ionization constants Ka and Kb',
    'pH and pOH definitions',
    'Buffer solutions and buffer capacity',
    'Henderson-Hasselbalch equation',
    'Titration and neutralization reactions',
    'Solubility product and precipitation',
    'Common ion effect',
  ]),
  chapter(8, 11, 'Redox Reactions', [
    'Oxidation and reduction definitions',
    'Oxidation number rules and assignment',
    'Oxidizing and reducing agents',
    'Balancing redox equations',
    'Half-reaction method',
    'Oxidation state method',
    'Disproportionation reactions',
    'Comproportionation reactions',
    'Ionic equations and molecular equations',
    'Redox pairs and electrode potentials',
    'Standard reduction potentials',
  ]),
  chapter(9, 11, 'Hydrogen', [
    'Position of hydrogen in periodic table',
    'Isotopes of hydrogen',
    'Hydrogen atom and hydrogen molecule',
    'Electron configuration and properties',
    'Hydride formation and types of hydrides',
    'Ionic hydrides',
    'Covalent hydrides',
    'Metallic hydrides and interstitial compounds',
    'Water structure and properties',
    'Heavy water (D2O)',
    'Hydrogen peroxide and decomposition',
    'Uses and properties of H2O2',
    'Hydrogen as a fuel',
    'Hydrogen storage and applications',
    'Hydrogen in industry',
  ]),
  chapter(10, 11, 'The s-Block Elements', [
    'General properties of alkali metals',
    'Lithium and anomalous properties',
    'Sodium and potassium',
    'Important compounds: NaCl, KCl',
    'Sodium carbonate and sodium bicarbonate',
    'Potassium permanganate',
    'Alkaline earth metals',
    'Beryllium and anomalous properties',
    'Magnesium and calcium',
    'Important compounds: CaCO3, Ca(OH)2',
    'Calcium sulfate and gypsum',
    'Biological importance of s-block elements',
    'Industrial uses and applications',
  ]),
  chapter(11, 11, 'The p-Block Elements (Groups 13 and 14)', [
    'General properties of p-block',
    'Group 13: Boron and aluminum',
    'Boron compounds and borax',
    'Aluminum oxide and aluminum hydroxide',
    'Aluminum salts and alums',
    'Group 14: Carbon and silicon',
    'Allotropes of carbon',
    'Diamond and graphite structures',
    'Silicon dioxide and silicates',
    'Silicones and their properties',
    'Catenation in carbon and silicon',
    'Anomalous properties of boron and carbon',
    'Oxides, halides and hydrides',
    'Chemical reactivity trends',
  ]),
  chapter(12, 11, 'Organic Chemistry - Some Basic Principles and Techniques', [
    'General introduction to organic chemistry',
    'Classification of organic compounds',
    'Structural formulae: empirical, molecular, structural',
    'Purification methods: distillation, crystallization',
    'Extraction and chromatography',
    'Qualitative analysis methods',
    'Quantitative analysis: estimation',
    'IUPAC nomenclature basics',
    'Homologous series and functional groups',
    'Electronic effects: inductive, resonance',
    'Mesomerism and resonance structures',
    'Aromaticity and Hückel rule',
    'Bond fission: homolytic and heterolytic',
    'Reaction intermediates: radicals, carbanions, carbocations',
    'Stability of intermediates',
    'Reaction mechanisms and elementary steps',
    'Factor affecting reaction rate',
  ]),
  chapter(13, 11, 'Hydrocarbons', [
    'Alkane classification and nomenclature',
    'Structure of alkanes and isomerism',
    'Preparation of alkanes: reduction, decarboxylation',
    'Alkane properties and combustion',
    'Free radical reactions and halogenation',
    'Alkene structure and nomenclature',
    'Preparation of alkenes: dehydration, elimination',
    'Alkene reactions: addition reactions',
    'Markovnikov rule and carbocation stability',
    'Anti-Markovnikov additions',
    'Hydrogenation and oxidation of alkenes',
    'Alkyne structure and nomenclature',
    'Preparation of alkynes',
    'Alkyne reactions and acidic nature',
    'Aromatic hydrocarbons and benzene',
    'Resonance and stability of benzene',
    'Aromaticity and Hückel rule',
    'Isomerism in aromatic compounds',
    'Sources: coal tar and petroleum',
  ]),
  chapter(14, 11, 'Environmental Chemistry', [
    'Atmosphere composition and layers',
    'Atmospheric pressure and temperature',
    'Air pollution sources and types',
    'Particulate matter and harmful gases',
    'Smog formation and photochemical smog',
    'Ozone layer and depletion',
    'Chlorofluorocarbons (CFCs)',
    'Greenhouse effect and global warming',
    'Carbon dioxide and climate change',
    'Acid rain and pH effects',
    'Water pollution and contaminants',
    'Water purification methods',
    'Soil pollution and degradation',
    'Contamination and remediation',
    'Green chemistry principles',
    'Prevention and waste reduction',
    'Alternative materials and processes',
  ]),
];

const chemistryClass12: CurriculumChapter[] = [
  chapter(1, 12, 'Solid State', [
    'Crystalline and amorphous solids',
    'Crystal lattices and unit cells',
    'Lattice types: cubic, hexagonal, tetragonal',
    'Simple cubic, body-centered, face-centered',
    'Packing efficiency and density',
    'Point defects: Schottky and Frenkel',
    'Line and plane defects',
    'Electrical and thermal properties',
    'Magnetic properties of solids',
    'Optical properties and color',
    'X-ray crystallography and diffraction',
  ]),
  chapter(2, 12, 'Solutions', [
    'Types of solutions: solid, liquid, gas',
    'Molarity, molality and mole fraction',
    'Normality and equivalent weight',
    'Mass percentage and PPM',
    'Vapor pressure lowering',
    'Raoult law and its applications',
    'Ideal and non-ideal solutions',
    'Partial pressure and Raoult law for gases',
    'Colligative properties',
    'Elevation of boiling point',
    'Depression of freezing point',
    'Osmotic pressure and van t\'Hoff equation',
    'Semi-permeable membrane concept',
    'Osmosis and dialysis',
    'Abnormal molecular mass',
    'Van der Waals factor and association/dissociation',
  ]),
  chapter(3, 12, 'Electrochemistry', [
    'Galvanic and electrolytic cells',
    'Anode and cathode definition',
    'Oxidation at anode and reduction at cathode',
    'EMF and electrode potential',
    'Standard reduction potentials',
    'Nernst equation and applications',
    'Electrochemical series',
    'Galvanic cell calculations',
    'Conductance and conductivity',
    'Strong and weak electrolytes',
    'Molar conductivity',
    'Kohlrausch law and limiting molar conductivity',
    'Batteries and types',
    'Primary and secondary batteries',
    'Fuel cells',
    'Corrosion and corrosion prevention',
    'Electroplating and electrorefining',
    'Faraday laws of electrolysis',
  ]),
  chapter(4, 12, 'Chemical Kinetics', [
    'Rate of reaction: average and instantaneous',
    'Factors affecting reaction rate',
    'Rate law and rate constant',
    'Order of reaction: zero, first, second',
    'Molecularity and mechanism',
    'Integrated rate equations',
    'Half-life and reaction order',
    'Arrhenius equation',
    'Activation energy and temperature dependence',
    'Collision theory basics',
    'Orientation factor and effective collision',
    'Catalysis and catalysts',
    'Homogeneous catalysis',
    'Heterogeneous catalysis',
    'Enzyme catalysis basics',
    'Reaction mechanisms and intermediate species',
  ]),
  chapter(5, 12, 'Surface Chemistry', [
    'Adsorption and absorption',
    'Physical adsorption vs chemical',
    'Adsorption isotherms',
    'Freundlich and Langmuir isotherms',
    'Catalysis at surfaces',
    'Enzyme catalysis and specificity',
    'Colloids and their classification',
    'Lyophilic and lyophobic colloids',
    'Colloidal stability and zeta potential',
    'Emulsions and types',
    'Gels and gel formation',
    'Aerosols and disperse systems',
    'Tyndall effect and properties',
    'Coagulation and peptization',
    'Applications in industry',
  ]),
  chapter(6, 12, 'General Principles and Processes of Isolation of Elements', [
    'Occurrence of elements',
    'Mineral and ore classification',
    'Concentration of ores: magnetic, flotation',
    'Roasting and calcination processes',
    'Reduction methods',
    'Carbon reduction and displacement',
    'Electrochemical reduction',
    'Refining and purification',
    'Extraction of iron: blast furnace',
    'Extraction of aluminum: Bayer and Hall process',
    'Extraction of copper: smelting and electrolysis',
    'Metallurgy of zinc and lead',
    'Thermodynamic and kinetic feasibility',
  ]),
  chapter(7, 12, 'The p-Block Elements', [
    'Group 15: Nitrogen and phosphorus',
    'Nitrogen chemistry and oxides',
    'Phosphorus and its allotropes',
    'Phosphoric acid and phosphates',
    'Group 16: Oxygen and sulfur',
    'Ozone structure and reactions',
    'Sulfuric acid manufacture',
    'Group 17: Halogens',
    'Halogen reactivity and trends',
    'Halogen compounds and oxides',
    'Hydrogen halides and hydracids',
    'Group 18: Noble gases',
    'Noble gas compounds',
    'Fluorine compounds of noble gases',
    'Uses and applications of noble gases',
  ]),
  chapter(8, 12, 'The d- and f-Block Elements', [
    'Transition elements and d-block',
    'Electronic configuration',
    'Oxidation states and variable oxidation',
    'General properties: color, magnetism',
    'Complex formation and coordination',
    'Lanthanoids and actinoids',
    'Lanthanide contraction',
    'Actinoid elements and radioactivity',
    'Important transition metal compounds',
    'Permanganate and dichromate',
    'Uses of transition metals',
    'Alloy formation and applications',
  ]),
  chapter(9, 12, 'Coordination Compounds', [
    'Ligands and coordination number',
    'Nomenclature rules and naming',
    'Isomerism: structural and stereoisomerism',
    'Geometrical isomerism',
    'Optical isomerism',
    'Coordinate covalent bond',
    'Crystal field theory basics',
    'Octahedral complexes and splitting',
    'Tetrahedral complexes',
    'Square planar complexes',
    'Color in coordination compounds',
    'Magnetic properties and spin',
    'Bonding in complexes: VBT and CFT',
    'Stability of complexes',
    'Applications of coordination compounds',
  ]),
  chapter(10, 12, 'Haloalkanes and Haloarenes', [
    'Nomenclature and classification',
    'Preparation of haloalkanes',
    'From alkenes and alkanes',
    'From alcohols using various reagents',
    'Physical properties of haloalkanes',
    'Nucleophilic substitution reactions',
    'SN1 and SN2 mechanisms',
    'Substrate and nucleophile effects',
    'Elimination reactions and regioselectivity',
    'E1 and E2 mechanisms',
    'Hofmann and Zaitsev rule',
    'Competition between substitution and elimination',
    'Preparation of haloarenes',
    'Aryl halides and substitution',
    'Nucleophilic aromatic substitution',
    'Environmental effects of halogenated compounds',
  ]),
  chapter(11, 12, 'Alcohols, Phenols and Ethers', [
    'Classification and nomenclature',
    'Preparation of alcohols',
    'From alkenes and alkyl halides',
    'From carbonyl reduction',
    'Fermentation processes',
    'Primary, secondary and tertiary alcohols',
    'Physical properties and hydrogen bonding',
    'Polyhydric alcohols',
    'Reactions of alcohols',
    'Oxidation to carbonyl compounds',
    'Esterification reactions',
    'Acidity of alcohols and phenols',
    'Phenols and aromaticity',
    'Phenolic OH and acidity',
    'Important phenol reactions',
    'Kolbe reaction and Reimer-Tiemann',
    'Ethers nomenclature and preparation',
    'Williamson ether synthesis',
    'Cleavage of ethers',
  ]),
  chapter(12, 12, 'Aldehydes, Ketones and Carboxylic Acids', [
    'Nomenclature and classification',
    'Preparation of aldehydes and ketones',
    'Oxidation and reduction',
    'From alkenes and alkynes',
    'Friedel-Crafts acylation',
    'Physical properties and polarity',
    'Nucleophilic addition reactions',
    'Addition of HCN and Grignard',
    'Aldol condensation',
    'Cannizzaro reaction',
    'Aldehyde and ketone reactions',
    'Oxidation reactions',
    'Reduction to alcohols',
    'Carboxylic acids nomenclature',
    'Preparation of carboxylic acids',
    'From alcohols and alkyl halides',
    'From nitriles and amides',
    'From esters and acid anhydrides',
    'Physical properties and dimerization',
    'Acidity of carboxylic acids',
    'Carboxylic acid reactions',
    'Esterification and decarboxylation',
    'Acid derivatives: esters, anhydrides, chlorides',
  ]),
  chapter(13, 12, 'Amines', [
    'Classification and nomenclature',
    'Primary, secondary and tertiary amines',
    'Preparation of amines',
    'Reduction of nitro compounds',
    'From alkyl halides and ammonia',
    'From carboxylic acids',
    'Physical properties and bonding',
    'Basicity of amines',
    'Electron-donating groups effect',
    'Comparative basicity of anilines',
    'Reactions of amines',
    'Acylation and alkylation',
    'Diazonium salts formation',
    'Sandmeyer and related reactions',
    'Diazo coupling and azo compounds',
    'Amine derivatives and importance',
    'Amino groups in biomolecules',
  ]),
  chapter(14, 12, 'Biomolecules', [
    'Carbohydrates: classification',
    'Monosaccharides and isomerism',
    'Glucose and fructose',
    'Disaccharides: sucrose, maltose, lactose',
    'Polysaccharides: starch, cellulose, glycogen',
    'Mutarotation and glycosidic bonds',
    'Proteins: amino acids',
    'Alpha amino acids and zwitterions',
    'Peptide linkage and peptides',
    'Polypeptides and protein structure',
    'Primary, secondary, tertiary structure',
    'Tertiary structure: alpha helix, beta sheet',
    'Quaternary structure and protein properties',
    'Fibrous and globular proteins',
    'Lipids: classification',
    'Saturated and unsaturated fats',
    'Phospholipids and membranes',
    'Vitamins: water and fat-soluble',
    'Coenzymes and their roles',
    'Nucleic acids: DNA and RNA',
    'Nucleotides and bases',
    'DNA structure and replication',
    'RNA types and functions',
  ]),
  chapter(15, 12, 'Polymers', [
    'Classification of polymers',
    'Natural and synthetic polymers',
    'Polymerization reactions',
    'Addition polymerization',
    'Vinyl polymerization',
    'Condensation polymerization',
    'Degree of polymerization',
    'Important addition polymers',
    'Polyethylene, PVC, PTFE',
    'Polystyrene and polybutadiene',
    'Important condensation polymers',
    'Polyesters and polyamides',
    'Nylon and Dacron',
    'Bakelite and urea-formaldehyde',
    'Biodegradable polymers',
    'Polymer properties and applications',
    'Elasticity, crystallinity, melting point',
    'Industrial polymers and uses',
  ]),
  chapter(16, 12, 'Chemistry in Everyday Life', [
    'Drugs and medicines',
    'Aspirin and analgesics',
    'Antibiotics and antimicrobials',
    'Antiseptics and disinfectants',
    'Common antiseptics: alcohol, iodine',
    'Boric acid and hydrogen peroxide',
    'Food preservatives and additives',
    'Antioxidants and their role',
    'Artificial sweeteners',
    'Food colors and additives',
    'Detergents and soaps',
    'Anionic and cationic detergents',
    'Surfactants and properties',
    'Washing action mechanism',
    'Cleaning products and composition',
    'Bleaching agents and bleaching',
    'Oxidizing and reducing bleaches',
    'Chemicals in agriculture',
    'Fertilizers: nitrogen, phosphate, potassa',
    'Pesticides and herbicides',
  ]),
];

const mathematicsClass11: CurriculumChapter[] = [
  chapter(1, 11, 'Sets', [
    'Set notation and representation',
    'Roster and builder form',
    'Types of sets: finite, infinite, null, universal',
    'Subsets and proper subsets',
    'Power set and its elements',
    'Cardinality of sets',
    'Equal and equivalent sets',
    'Operations on sets: union, intersection',
    'Complement of a set',
    'De Morgan laws and set identities',
    'Venn diagrams and set relationships',
    'Ordered pairs and relations',
    'Cartesian product of sets',
  ]),
  chapter(2, 11, 'Relations and Functions', [
    'Relations and domain-range',
    'Types of relations: reflexive, symmetric, transitive',
    'Equivalence relations',
    'Functions and mappings',
    'Domain, codomain and range',
    'Function notation and representation',
    'Types of functions: one-one, onto, bijective',
    'Inverse functions',
    'Composition of functions',
    'Binary operations',
    'Properties of binary operations',
    'Identity and inverse elements',
  ]),
  chapter(3, 11, 'Trigonometric Functions', [
    'Angles and their measurements',
    'Degree and radian conversion',
    'Trigonometric ratios: sin, cos, tan, cot, sec, cosec',
    'Reciprocal trigonometric functions',
    'Trigonometric ratios for standard angles',
    'Trigonometric identities: Pythagorean',
    'Sum and difference formulas',
    'Multiple angle formulas: 2A, 3A',
    'Half-angle formulas',
    'Product-to-sum and sum-to-product formulas',
    'Graphs of trigonometric functions',
    'Periodicity of trigonometric functions',
    'Transformations of trigonometric graphs',
    'Trigonometric equations',
    'Principal and general solutions',
    'Inverse trigonometric functions',
    'Inverse trigonometric equations',
  ]),
  chapter(4, 11, 'Principle of Mathematical Induction', [
    'Mathematical statements and propositions',
    'Proof by induction principle',
    'Base case and inductive step',
    'Induction on natural numbers',
    'Strong induction',
    'Induction on divisibility problems',
    'Induction on inequalities',
    'Induction on sums and series',
    'Fibonacci sequence via induction',
    'Binomial theorem proof via induction',
  ]),
  chapter(5, 11, 'Complex Numbers and Quadratic Equations', [
    'Complex numbers and imaginary unit',
    'Real and imaginary parts',
    'Algebra of complex numbers',
    'Addition, subtraction, multiplication, division',
    'Conjugate and modulus',
    'Argand plane and geometric representation',
    'Polar form of complex number',
    'De Moivre theorem',
    'Roots of complex numbers',
    'Nth roots of unity',
    'Quadratic equations and roots',
    'Nature of roots: discriminant',
    'Real and complex roots',
    'Sum and product of roots',
    'Formation of quadratic equations',
    'Vieta formulas and applications',
  ]),
  chapter(6, 11, 'Linear Inequalities', [
    'Inequalities and properties',
    'Linear inequalities in one variable',
    'Solution sets and interval notation',
    'Graphical solution of inequalities',
    'Compound inequalities',
    'Inequalities in two variables',
    'System of linear inequalities',
    'Feasible region determination',
    'Graphical method for two variables',
    'Properties of inequalities',
    'Absolute value inequalities',
  ]),
  chapter(7, 11, 'Permutations and Combinations', [
    'Fundamental principle of counting',
    'Permutation definition and formula',
    'Permutations with restrictions',
    'Circular permutations',
    'Permutations with repetition',
    'Combination definition and formula',
    'Combinations with restrictions',
    'Relationship between nPr and nCr',
    'Pascals triangle and combinations',
    'Selections and arrangements',
    'Dividing into groups',
    'Distributing identical and distinct objects',
  ]),
  chapter(8, 11, 'Binomial Theorem', [
    'Binomial expansion for positive integer',
    'Binomial coefficients',
    'Pascal identity and triangle',
    'General term in expansion',
    'Middle term and greatest term',
    'Specific term extraction',
    'Binomial series for rational exponent',
    'Applications to approximations',
    'Multinomial expansion basics',
    'Binomial identities and properties',
  ]),
  chapter(9, 11, 'Sequences and Series', [
    'Sequence as a function',
    'Arithmetic progression and common difference',
    'nth term and sum of AP',
    'Geometric progression and common ratio',
    'nth term and sum of GP',
    'Infinite geometric series and convergence',
    'Harmonic progression',
    'Arithmetic-geometric progressions',
    'Special series: natural numbers, squares, cubes',
    'Telescoping series',
    'Series summation techniques',
  ]),
  chapter(10, 11, 'Straight Lines', [
    'Coordinate system and plotting',
    'Distance formula and section formula',
    'Slope and angle of inclination',
    'Equation of line: point-slope form',
    'Slope-intercept form',
    'Two-point form and intercept form',
    'General form of line',
    'Parallel and perpendicular lines',
    'Angle between two lines',
    'Distance of point from line',
    'Family of lines passing through point',
    'Equation of line through intersection',
  ]),
  chapter(11, 11, 'Conic Sections', [
    'Circle: center, radius, equation',
    'Circle from center and point',
    'General equation of circle',
    'Chord and tangent to circle',
    'Parabola: definition and focus-directrix',
    'Standard equation of parabola',
    'Vertex, focus, directrix, axis',
    'Latus rectum and parameter',
    'Ellipse: definition and foci',
    'Standard equation of ellipse',
    'Eccentricity and relationship',
    'Major and minor axes',
    'Hyperbola: definition and foci',
    'Standard equation of hyperbola',
    'Asymptotes and eccentricity',
    'Rectangular hyperbola',
    'Conjugate axes and transverse axis',
  ]),
  chapter(12, 11, 'Introduction to Three Dimensional Geometry', [
    'Coordinate axes and planes in 3D',
    'Distance formula in 3D',
    'Section formula and midpoint',
    'Direction cosines and ratios',
    'Relationship between direction cosines',
    'Angle between two lines',
    'Skew lines and shortest distance',
    'Equation of line in 3D',
    'Symmetric and parametric forms',
    'Plane equation: general form',
    'Normal form and intercept form',
    'Angle between planes',
    'Distance from point to plane',
  ]),
  chapter(13, 11, 'Limits and Derivatives', [
    'Concept of limit and definition',
    'One-sided limits',
    'Algebra of limits',
    'Limit properties and theorems',
    'Sandwich theorem',
    'Continuity at a point',
    'Discontinuity types',
    'Continuity on intervals',
    'Derivative definition and interpretation',
    'Derivative as rate of change',
    'Derivative as slope of tangent',
    'Algebra of derivatives',
    'Derivative of polynomial functions',
    'Derivative of trigonometric functions',
    'Derivative of exponential and logarithmic',
    'Chain rule and composite functions',
    'Product and quotient rules',
    'Higher order derivatives',
  ]),
  chapter(14, 11, 'Mathematical Reasoning', [
    'Statement and truth value',
    'Compound statements',
    'Logical connectives: AND, OR, NOT',
    'Conditional: if-then statement',
    'Converse, inverse and contrapositive',
    'Biconditional: if and only if',
    'Tautology and contradiction',
    'Logical equivalence',
    'Quantifiers: universal and existential',
    'Validity of arguments',
    'Types of mathematical proof',
    'Direct proof and proof by contradiction',
    'Mathematical induction as proof',
  ]),
  chapter(15, 11, 'Statistics', [
    'Data collection and classification',
    'Frequency distribution',
    'Grouped and ungrouped data',
    'Mean, median and mode',
    'Properties of measures of central tendency',
    'Range and interquartile range',
    'Variance and standard deviation',
    'Coefficient of variation',
    'Properties of variance',
    'Cumulative frequency and percentiles',
    'Cumulative frequency distribution',
    'Histograms and frequency polygons',
    'Ogives and graphical representation',
  ]),
  chapter(16, 11, 'Probability', [
    'Random experiment and sample space',
    'Event and elementary event',
    'Certain and impossible events',
    'Mutually exclusive events',
    'Complementary events',
    'Classical probability definition',
    'Equally likely outcomes',
    'Addition rule of probability',
    'Multiplication rule of probability',
    'Conditional probability',
    'Independent events',
    'Total probability and Bayes theorem',
  ]),
];

const mathematicsClass12: CurriculumChapter[] = [
  chapter(1, 12, 'Inverse Trigonometric Functions', [
    'Inverse trigonometric functions definition',
    'Domain and range of inverse functions',
    'Principal value branches',
    'Inverse sine and inverse cosine',
    'Inverse tangent and inverse cotangent',
    'Inverse secant and inverse cosecant',
    'Properties of inverse trigonometric functions',
    'Composition of inverse functions',
    'Identities involving inverse functions',
    'Graphs of inverse trigonometric functions',
    'Inverse trigonometric equations',
  ]),
  chapter(2, 12, 'Matrices', [
    'Matrix notation and order',
    'Types of matrices: row, column, square, rectangular',
    'Triangular matrices and diagonal',
    'Scalar and unit matrices',
    'Matrix operations: addition and subtraction',
    'Scalar multiplication of matrices',
    'Matrix multiplication and properties',
    'Commutative and distributive properties',
    'Transpose of matrix',
    'Symmetric and skew-symmetric matrices',
    'Trace of matrix',
    'Inverse of matrix',
    'Methods for finding inverse',
    'Orthogonal matrices',
  ]),
  chapter(3, 12, 'Determinants', [
    'Determinant of a square matrix',
    'Determinants of 2x2 and 3x3 matrices',
    'Properties of determinants',
    'Multiplication theorem for determinants',
    'Row and column operations',
    'Minors and cofactors',
    'Adjoint of a matrix',
    'Relationship between adjoint and inverse',
    'Singular and non-singular matrices',
    'System of linear equations',
    'Solving equations using determinants',
    'Cramer rule and applications',
    'Homogeneous system of equations',
    'Consistency of system',
  ]),
  chapter(4, 12, 'Continuity and Differentiability', [
    'Continuity at a point definition',
    'Left and right continuity',
    'Continuity on an interval',
    'Discontinuity types: removable, jump, infinite',
    'Algebra of continuous functions',
    'Continuous functions on closed intervals',
    'Differentiability at a point',
    'Left and right derivatives',
    'Relationship between continuity and differentiability',
    'Derivatives of composite functions: chain rule',
    'Logarithmic differentiation',
    'Derivatives of inverse trigonometric functions',
    'Derivatives of exponential functions',
    'Derivatives of logarithmic functions',
    'Implicit differentiation',
    'Parametric differentiation',
  ]),
  chapter(5, 12, 'Applications of Derivatives', [
    'Increasing and decreasing functions',
    'Monotonicity and derivative test',
    'Equation of tangent and normal',
    'Angle between two curves',
    'Maxima and minima: local and global',
    'First derivative test',
    'Second derivative test',
    'Optimization problems',
    'Rate of change and related rates',
    'Approximation and linear approximation',
    'Differential and error estimation',
    'Curve sketching and asymptotes',
  ]),
  chapter(6, 12, 'Integrals', [
    'Indefinite integral and antiderivative',
    'Constant of integration',
    'Properties of indefinite integrals',
    'Integral of standard functions',
    'Integral of reciprocals',
    'Integration by substitution',
    'Integration by parts',
    'ILATE rule for choosing parts',
    'Partial fractions method',
    'Linear, quadratic and repeated factors',
    'Definite integrals and properties',
    'Fundamental theorem of calculus',
    'Evaluation of definite integrals',
    'Upper and lower limits',
  ]),
  chapter(7, 12, 'Applications of Integrals', [
    'Area under curves',
    'Area between two curves',
    'Bounded regions and area calculation',
    'Definite integral as limit of sums',
    'Riemann sums',
    'Geometrical applications',
    'Area of plane figures',
    'Volume of solids of revolution',
    'Disk and washer method',
    'Shell method for volume',
  ]),
  chapter(8, 12, 'Differential Equations', [
    'Differential equation definition',
    'Order and degree of DE',
    'Formation of differential equations',
    'Elimination of arbitrary constants',
    'Separable differential equations',
    'Variables separation method',
    'Homogeneous differential equations',
    'Homogeneity test',
    'First-order linear differential equations',
    'Standard form and integrating factor',
    'Bernoulli equation',
    'Exact differential equations',
    'Conditional verification',
    'Applications to population, cooling, circuit',
  ]),
  chapter(9, 12, 'Vector Algebra', [
    'Vectors and scalars',
    'Representation of vectors',
    'Magnitude and direction',
    'Unit vectors and basis vectors',
    'Position vectors',
    'Addition and subtraction of vectors',
    'Scalar multiplication of vectors',
    'Scalar or dot product',
    'Properties of dot product',
    'Projection of vectors',
    'Vector or cross product',
    'Properties of cross product',
    'Scalar triple product',
    'Vector triple product',
    'Application to area and volume',
  ]),
  chapter(10, 12, 'Three Dimensional Geometry', [
    'Direction cosines and ratios',
    'Relationships and properties',
    'Equation of line through a point',
    'Symmetric form of line equation',
    'Parametric form of line',
    'Angle between two lines',
    'Equation of plane general form',
    'Normal form of plane',
    'Intercept form of plane',
    'Angle between two planes',
    'Angle between line and plane',
    'Distance of point from plane',
    'Distance between skew lines',
    'Foot of perpendicular',
    'Coplanarity of lines',
  ]),
  chapter(11, 12, 'Linear Programming', [
    'Linear inequalities in two variables',
    'Graphical solution of inequalities',
    'Feasible region and vertices',
    'Linear programming problem',
    'Objective function',
    'Constraints and bounded region',
    'Corner point method',
    'Optimum value at vertices',
    'Unbounded regions',
    'Multiple solutions in LP',
    'Maximization and minimization',
    'Applications to resource allocation',
    'Transportation and assignment problems',
  ]),
  chapter(12, 12, 'Probability', [
    'Conditional probability',
    'Compound probability',
    'Multiplication theorem',
    'Independent events',
    'Dependent events',
    'Total probability theorem',
    'Bayes theorem and applications',
    'Prior and posterior probability',
    'Random variables and distribution',
    'Discrete and continuous distributions',
    'Probability mass function',
    'Probability density function',
    'Cumulative distribution function',
    'Mathematical expectation',
    'Variance and standard deviation',
    'Binomial distribution',
    'Parameters of binomial distribution',
    'Normal distribution basics',
  ]),
];

const biologyClass11: CurriculumChapter[] = [
  chapter(1, 11, 'The Living World', [
    'Living organisms and characteristics of life',
    'Metabolism and energy transformation',
    'Growth, reproduction and heredity',
    'Response to environment and homeostasis',
    'Organization levels in biology',
    'Biosphere, ecosystem, community, population',
    'Organism level organization',
    'Biodiversity and megadiversity hotspots',
    'Species concept and classification',
    'Taxonomy and taxonomic hierarchy',
    'Binomial nomenclature rules',
    'Scientific names and standardization',
    'Systematic classification',
  ]),
  chapter(2, 11, 'Biological Classification', [
    'Evolution of classification systems',
    'Five kingdom classification',
    'Kingdom Monera and prokaryotes',
    'Bacteria: shapes, types and reproduction',
    'Cyanobacteria and photosynthetic bacteria',
    'Archaea and extremophiles',
    'Kingdom Protista and protozoans',
    'Algae: classification and life cycles',
    'Flagellated, ciliated, sporozoans',
    'Slime molds and plasmodial network',
    'Kingdom Fungi: structure and reproduction',
    'Ascomycetes, basidiomycetes, zygomycetes',
    'Fungi in ecology: decomposers',
    'Economic importance of fungi',
    'Lichens: symbiotic association',
    'Viruses and viral structure',
    'Viroids and prions',
  ]),
  chapter(3, 11, 'Plant Kingdom', [
    'Plant diversity and evolution',
    'Algae: major groups and life cycles',
    'Green algae and bryophytes transition',
    'Bryophytes: mosses and liverworts',
    'Bryophyte structure and habitat',
    'Pteridophytes: ferns and allies',
    'Vascular tissue development',
    'Alternation of generations',
    'Sporophyte dominance',
    'Gymnosperms: cycads, conifers, gnetophytes',
    'Seeds and seed coat',
    'Pollen and pollination',
    'Angiosperms: flowering plants',
    'Double fertilization',
    'Fruit and seed development',
    'Dicots and monocots',
  ]),
  chapter(4, 11, 'Animal Kingdom', [
    'Animal characteristics and classification',
    'Symmetry: radial and bilateral',
    'Coelom types: acoelomate, pseudocoelomate, coelomate',
    'Segmentation in animals',
    'Notochord and vertebral column',
    'Porifera: sponges and canal systems',
    'Cnidaria: coelenterates and stinging cells',
    'Platyhelminthes: flatworms',
    'Parasitic worms and diseases',
    'Nematoda: roundworms',
    'Annelida: segmented worms',
    'Arthropoda: insects, crustaceans, arachnids',
    'Mollusca: snails, clams, octopus',
    'Echinodermata: starfish, sea urchins',
    'Chordata: vertebrate subphylum',
    'Fish, amphibians, reptiles, birds, mammals',
  ]),
  chapter(5, 11, 'Morphology of Flowering Plants', [
    'Plant body organization',
    'Root systems and root modifications',
    'Aerial roots and specialized roots',
    'Stem structure and modifications',
    'Underground stems: rhizomes, corms, tubers',
    'Leaf morphology: simple and compound',
    'Leaf phyllotaxy and arrangement patterns',
    'Leaf venation: parallel and reticulate',
    'Meso phyll and stomata',
    'Flower structure and parts',
    'Inflorescence types and arrangements',
    'Aestivation patterns',
    'Placentation types',
    'Fruit types and seed dispersal',
    'Pollination mechanisms and vectors',
  ]),
  chapter(6, 11, 'Anatomy of Flowering Plants', [
    'Plant tissues: meristematic and permanent',
    'Apical, lateral and intercalary meristems',
    'Epidermal tissue and its modifications',
    'Trichomes and scales',
    'Stomata and gas exchange',
    'Ground tissue: parenchyma, collenchyma, sclerenchyma',
    'Vascular tissue: xylem and phloem',
    'Xylem vessels and tracheids',
    'Phloem: sieve tubes and companion cells',
    'Dicot root anatomy',
    'Monocot root anatomy',
    'Dicot stem anatomy',
    'Monocot stem anatomy',
    'Dicot leaf anatomy',
    'Monocot leaf anatomy',
    'Primary and secondary growth',
    'Vascular cambium and cork cambium',
    'Annual rings and dendrochronology',
  ]),
  chapter(7, 11, 'Structural Organisation in Animals', [
    'Animal tissue types: epithelial, connective, muscular, nervous',
    'Epithelial tissue and types',
    'Simple and stratified epithelium',
    'Specialized epithelial cells',
    'Connective tissue: proper connective tissues',
    'Areolar, adipose, and fibrous tissue',
    'Bone structure and ossification',
    'Cartilage types: hyaline, fibrous, elastic',
    'Blood composition and cell types',
    'Muscular tissue: skeletal, cardiac, smooth',
    'Muscle fiber structure and contraction',
    'Nervous tissue: neurons and neuroglia',
    'Synapse and neurotransmission',
    'Earthworm anatomy and dissection',
    'Cockroach anatomy and organization',
    'Frog anatomy and systems',
  ]),
  chapter(8, 11, 'Cell: The Unit of Life', [
    'Cell theory and cell discovery',
    'Unicellular and multicellular organisms',
    'Prokaryotic cell structure',
    'Eukaryotic cell structure',
    'Cell size and shape diversity',
    'Plasma membrane structure and function',
    'Fluid mosaic model',
    'Membrane transport: diffusion and osmosis',
    'Active transport and carrier proteins',
    'Cell wall composition and function',
    'Nucleus: structure and components',
    'Nucleolus and ribosomal synthesis',
    'Chromatin organization',
    'Endoplasmic reticulum: rough and smooth',
    'Golgi apparatus and vesicles',
    'Lysosomes and hydrolytic enzymes',
    'Mitochondria structure and function',
    'Chloroplasts and photosynthesis',
    'Vacuoles: contractile and storage',
    'Cytoplasm and cytosol',
    'Ribosomes and protein synthesis',
    'Centrioles and centrosome',
  ]),
  chapter(9, 11, 'Biomolecules', [
    'Carbohydrates: monosaccharides',
    'Glucose, fructose, galactose forms',
    'Disaccharides: structure and bonding',
    'Sucrose, maltose, lactose formation',
    'Polysaccharides: starch, glycogen, cellulose',
    'Starch as energy storage',
    'Glycogen in animal cells',
    'Cellulose in plant cell walls',
    'Proteins: amino acids and diversity',
    'Peptide bond formation',
    'Protein structure: primary, secondary',
    'Alpha helix, beta sheet structures',
    'Tertiary and quaternary structure',
    'Protein denaturation and refolding',
    'Lipids: saturated and unsaturated fats',
    'Phospholipids and membrane bilayer',
    'Cholesterol and steroids',
    'Nucleic acids: DNA and RNA',
    'Nucleotides and their components',
    'DNA double helix structure',
    'RNA types: mRNA, tRNA, rRNA',
    'Watson-Crick model',
    'Enzymes: characteristics and properties',
    'Enzyme-substrate complex',
    'Cofactors and coenzymes',
  ]),
  chapter(10, 11, 'Cell Cycle and Cell Division', [
    'Cell cycle phases: G1, S, G2, M',
    'Interphase activities and DNA replication',
    'Restriction points and checkpoints',
    'G0 phase and cell differentiation',
    'Mitosis: phases and significance',
    'Prophase: chromatin condensation',
    'Metaphase: chromosome alignment',
    'Anaphase: sister chromatid separation',
    'Telophase: nuclear envelope reformation',
    'Cytokinesis in animal and plant cells',
    'Significance of mitosis in organisms',
    'Meiosis: reduction division',
    'Prophase I: crossing over and bivalent formation',
    'Metaphase I and anaphase I',
    'Meiosis II and tetrad formation',
    'Importance of meiosis in sexual reproduction',
    'Genetic variation and recombination',
    'Apoptosis and programmed cell death',
  ]),
  chapter(11, 11, 'Transport in Plants', [
    'Diffusion and osmosis in plant cells',
    'Imbibition and water absorption',
    'Turgidity and plasmolysis',
    'Water potential and solute potential',
    'Root absorption of water',
    'Root hair and absorption surface',
    'Capillary rise in soil',
    'Ascent of sap mechanisms',
    'Cohesion-tension theory',
    'Root pressure and guttation',
    'Transpiration and water loss',
    'Stomatal and cuticular transpiration',
    'Factors affecting transpiration rate',
    'Stomatal regulation and opening',
    'Translocation of photosynthates',
    'Phloem transport: mass flow hypothesis',
    'Sink and source cells',
    'Loading and unloading of phloem',
  ]),
  chapter(12, 11, 'Mineral Nutrition', [
    'Essential and non-essential elements',
    'Criteria for essentiality of elements',
    'Macronutrients: C, H, O, N, P, K',
    'Micronutrients: Fe, Mn, Cu, Zn, B, Mo, Cl',
    'Deficiency symptoms of nutrients',
    'Toxicity at excess concentrations',
    'Nitrogen fixation by bacteria',
    'Symbiotic nitrogen fixation: Rhizobium',
    'Free-living nitrogen fixers',
    'Nitrification and denitrification',
    'Nitrogen assimilation in plants',
    'Biological nitrogen cycle',
    'Phosphorus cycle',
    'Potassium cycle',
    'Mineral uptake: active and passive',
    'Root pressure and mineral absorption',
  ]),
  chapter(13, 11, 'Photosynthesis in Higher Plants', [
    'Photosynthetic pigments: chlorophyll',
    'Carotenoids and xanthophyll',
    'Light absorption spectrum',
    'Action spectrum and efficiency',
    'Light reaction in thylakoids',
    'Photolysis of water and oxygen evolution',
    'Photosystem I and II',
    'Electron transport chain',
    'Chemiosmotic hypothesis',
    'ATP synthesis and photophosphorylation',
    'Cyclic and non-cyclic photophosphorylation',
    'NADPH formation',
    'Dark reaction and Calvin cycle',
    'Carbon fixation by RuBisCO',
    'Reduction phase and product formation',
    'Regeneration of RuBP',
    'C3 plants and pathway',
    'C4 plants and photorespiration reduction',
    'CAM plants and water conservation',
    'Factors affecting photosynthesis',
    'Light saturation and compensation point',
  ]),
  chapter(14, 11, 'Respiration in Plants', [
    'Aerobic and anaerobic respiration',
    'Respiratory substrate and quotient',
    'Glycolysis in cytoplasm',
    'Glucose breakdown pathway',
    'Pyruvate oxidation and acetyl-CoA',
    'Krebs cycle intermediates',
    'Electron transfer chain oxidation',
    'Oxidative phosphorylation',
    'ATP yield from respiration',
    'Pentose phosphate pathway',
    'Fermentation: alcoholic and lactic acid',
    'Anaerobic pathways in plants',
    'Energy efficiency of different pathways',
    'Respiration rate and temperature',
    'Respiratory control and uncoupling',
  ]),
  chapter(15, 11, 'Plant Growth and Development', [
    'Growth and development concepts',
    'Apical dominance control',
    'Differentiation and determination',
    'Dedifferentiation and redifferentiation',
    'Plant growth regulators: hormones',
    'Auxins and apical dominance',
    'Gibberellins and stem elongation',
    'Cytokinins and cell division',
    'Ethylene and fruit ripening',
    'Abscisic acid and stress response',
    'Photoperiodism and flowering',
    'Short day and long day plants',
    'Vernalization and flowering',
    'Seed dormancy and germination',
    'Tropisms: gravitropism, phototropism',
    'Nastic movements',
    'Circadian rhythms in plants',
  ]),
  chapter(16, 11, 'Digestion and Absorption', [
    'Digestive system organization',
    'Mouth cavity and taste buds',
    'Salivary glands and enzyme secretion',
    'Esophagus and swallowing mechanism',
    'Stomach structure and functions',
    'Gastric juice and pepsin',
    'Small intestine: duodenum, jejunum, ileum',
    'Pancreatic juice and enzymes',
    'Bile production and emulsification',
    'Liver functions in digestion',
    'Enzyme digestion in small intestine',
    'Carbohydrate digestion and absorption',
    'Protein digestion and amino acid absorption',
    'Fat digestion and lipid absorption',
    'Mineral and vitamin absorption',
    'Water absorption in colon',
    'Bacterial flora and their role',
    'Digestive disorders and treatment',
  ]),
  chapter(17, 11, 'Breathing and Exchange of Gases', [
    'Respiratory system organization',
    'Nasal cavity and air filtration',
    'Trachea and bronchus',
    'Lungs and alveoli structure',
    'Diaphragm and intercostal muscles',
    'Mechanism of breathing: inspiration and expiration',
    'Pulmonary ventilation and volumes',
    'Vital capacity and breathing capacity',
    'Alveolar structure and gas exchange',
    'Oxygen diffusion into blood',
    'Carbon dioxide diffusion out',
    'Hemoglobin and oxygen binding',
    'Oxygen transport in blood',
    'Carbon dioxide transport mechanisms',
    'Bicarbonate buffer system',
    'Breathing control and regulation',
    'Chemoreceptors and CO2 sensing',
    'Respiratory disorders: asthma, emphysema',
  ]),
  chapter(18, 11, 'Body Fluids and Circulation', [
    'Blood composition and plasma',
    'Red blood cells and hemoglobin',
    'White blood cells and immunity',
    'Platelets and clotting',
    'Blood groups: ABO and Rh',
    'Blood clotting mechanism',
    'Lymph composition and circulation',
    'Tissue fluid formation',
    'Heart structure: chambers and valves',
    'Sinoatrial node and rhythm control',
    'Cardiac cycle: diastole and systole',
    'Heart sounds and cardiac output',
    'Blood vessels: arteries, veins, capillaries',
    'Arteriole and capillary network',
    'Blood pressure measurement',
    'Pulse and pulse pressure',
    'Double circulation in humans',
    'Coronary circulation',
    'Fetal circulation and placental exchange',
    'Circulation disorders: hypertension, atherosclerosis',
  ]),
  chapter(19, 11, 'Excretory Products and Their Elimination', [
    'Excretion and excretory products',
    'Kidney structure and nephron',
    'Glomerular filtration',
    'Selective reabsorption in loop of Henle',
    'Tubular secretion and collection duct',
    'Urine formation and final concentration',
    'Osmoregulation and ADH',
    'Countercurrent multiplier mechanism',
    'Urea and uric acid formation',
    'Kidney disease and dialysis',
    'Artificial kidney and hemofiltration',
    'Kidney transplantation',
    'Urinary system: ureters and bladder',
    'Micturition reflex',
    'Extrarenal excretion',
  ]),
  chapter(20, 11, 'Locomotion and Movement', [
    'Movement types and locomotion',
    'Skeletal system components',
    'Bone structure: compact and cancellous',
    'Osteocytes and bone matrix',
    'Bone formation: ossification',
    'Cartilage type and distribution',
    'Joints: fibrous, cartilaginous, synovial',
    'Synovial joint movement',
    'Skeleton organization',
    'Axial and appendicular skeleton',
    'Muscle tissue types',
    'Skeletal muscle structure',
    'Muscle fiber and sarcomere',
    'Sliding filament theory',
    'Muscle contraction mechanism',
    'Calcium and muscle contraction',
    'Motor neuron and neuromuscular junction',
    'Muscle fatigue and recovery',
    'Sports injuries and treatment',
  ]),
  chapter(21, 11, 'Neural Control and Coordination', [
    'Nervous system organization',
    'Central and peripheral nervous system',
    'Neuron structure and types',
    'Axon and dendrite organization',
    'Node of Ranvier and myelination',
    'Action potential propagation',
    'Resting potential and threshold',
    'Depolarization and repolarization',
    'Synapse structure and transmission',
    'Neurotransmitters and receptors',
    'Synaptic plasticity',
    'Central nervous system: brain and spinal cord',
    'Cerebrospinal fluid circulation',
    'Brain regions: cerebrum, cerebellum, brainstem',
    'Cerebral cortex and functions',
    'Memory formation and consolidation',
    'Sleep and wakefulness',
    'Spinal cord: gray and white matter',
    'Reflex arc and reflex response',
    'Peripheral nervous system',
    'Cranial and spinal nerves',
    'Somatic and autonomic nervous system',
    'Sympathetic and parasympathetic divisions',
  ]),
  chapter(22, 11, 'Chemical Coordination and Integration', [
    'Endocrine system and glands',
    'Hormone types and classification',
    'Peptide hormones and signaling',
    'Steroid hormones and lipid solubility',
    'Amino acid derivatives',
    'Mechanism of hormone action',
    'Receptor types and binding',
    'Signal transduction pathways',
    'Hypothalamus and brain control',
    'Pituitary gland: anterior and posterior',
    'Growth hormone and metabolism',
    'Thyroid gland and thyroid hormone',
    'Parathyroid and calcium regulation',
    'Adrenal gland: cortex and medulla',
    'Cortisol and stress response',
    'Epinephrine and fight-or-flight',
    'Pancreas: alpha and beta cells',
    'Insulin and glucose regulation',
    'Glucagon and blood sugar',
    'Diabetes mellitus: type 1 and type 2',
    'Feedback mechanisms and homeostasis',
    'Other endocrine tissues: thymus, pineal',
  ]),
];

const biologyClass12: CurriculumChapter[] = [
  chapter(1, 12, 'Reproduction in Organisms', [
    'Asexual reproduction and modes',
    'Sexual reproduction and gamete fusion',
    'Life span, senescence and death',
    'Reproductive strategies and cycles',
  ]),
  chapter(2, 12, 'Sexual Reproduction in Flowering Plants', [
    'Flower structure and reproductive organs',
    'Microsporogenesis and megasporogenesis',
    'Pollination and pollen-pistil interaction',
    'Double fertilisation and endosperm development',
    'Seed and fruit development',
  ]),
  chapter(3, 12, 'Human Reproduction', [
    'Male reproductive system and spermatogenesis',
    'Female reproductive system and oogenesis',
    'Menstrual cycle and hormonal control',
    'Fertilisation, implantation and pregnancy',
    'Parturition and lactation',
  ]),
  chapter(4, 12, 'Reproductive Health', [
    'Reproductive health and sex education',
    'Contraception and birth control methods',
    'Infertility and assisted reproductive technologies',
    'Population explosion and family welfare',
    'Maternal and child health',
  ]),
  chapter(5, 12, 'Principles of Inheritance and Variation', [
    'Mendel laws of inheritance',
    'Monohybrid and dihybrid crosses',
    'Inheritance patterns and pedigree analysis',
    'Sex determination and sex-linked inheritance',
    'Chromosomal disorders and mutations',
  ]),
  chapter(6, 12, 'Molecular Basis of Inheritance', [
    'DNA and RNA structure',
    'DNA replication and repair',
    'Transcription, processing and RNA types',
    'Genetic code and translation',
    'Gene regulation in prokaryotes and eukaryotes',
  ]),
  chapter(7, 12, 'Evolution', [
    'Origin of life and early earth conditions',
    'Evolutionary theories and natural selection',
    'Hardy-Weinberg principle and genetic equilibrium',
    'Speciation and adaptive radiation',
    'Evidences of evolution',
  ]),
  chapter(8, 12, 'Human Health and Disease', [
    'Pathogens, immunity and immune response',
    'Common infectious diseases',
    'Cancer, carcinogens and treatment',
    'AIDS, allergies and autoimmune disorders',
    'Drug abuse and preventive health',
  ]),
  chapter(9, 12, 'Strategies for Enhancement in Food Production', [
    'Plant breeding and crop improvement',
    'Animal breeding and selection methods',
    'Biofortification and improved varieties',
    'Single cell proteins and alternative food sources',
    'Horticulture and apiculture basics',
  ]),
  chapter(10, 12, 'Microbes in Human Welfare', [
    'Microbes in household products and fermentation',
    'Microbes in industry and biotechnology',
    'Sewage treatment and primary/secondary processing',
    'Biogas production and microbial energy',
    'Biocontrol and biofertilisers',
  ]),
  chapter(11, 12, 'Biotechnology: Principles and Processes', [
    'Principles of biotechnology and genetic engineering',
    'Restriction enzymes, vectors and cloning strategies',
    'PCR, gel electrophoresis and DNA fingerprinting',
    'Bioreactors and bioprocess engineering',
    'Downstream processing and product purification',
  ]),
  chapter(12, 12, 'Biotechnology and Its Applications', [
    'Biotechnology in agriculture',
    'Biotechnology in medicine and diagnostics',
    'Gene therapy and recombinant products',
    'Transgenic plants and animals',
    'Biosafety, ethics and biopiracy',
  ]),
  chapter(13, 12, 'Organisms and Populations', [
    'Organism responses and adaptations',
    'Population attributes and demographic structure',
    'Population growth models',
    'Species interactions and population regulation',
  ]),
  chapter(14, 12, 'Ecosystem', [
    'Ecosystem structure and components',
    'Productivity and energy flow',
    'Decomposition and mineral cycling',
    'Food chains, food webs and ecological pyramids',
    'Nutrient cycles and ecosystem stability',
  ]),
  chapter(15, 12, 'Biodiversity and Conservation', [
    'Biodiversity levels and measurement',
    'Patterns of biodiversity and hotspots',
    'Species loss and extinction drivers',
    'In-situ and ex-situ conservation',
    'Protected areas and conservation strategies',
  ]),
  chapter(16, 12, 'Environmental Issues', [
    'Air, water and soil pollution',
    'Solid waste management and e-waste',
    'Global warming, climate change and ozone depletion',
    'Noise pollution and control measures',
    'Environmental sustainability and waste reduction',
  ]),
];

// NEET-specific Physics (NCERT-aligned, simpler than JEE)
const neetPhysicsClass11: CurriculumChapter[] = [
  chapter(1, 11, 'Physical World and Measurements', [
    'Physical quantities and SI units',
    'Fundamental and derived units',
    'Dimensions and dimensional analysis',
    'Errors and significant figures',
    'Vernier caliper and screw gauge',
  ]),
  chapter(2, 11, 'Motion in One Dimension', [
    'Displacement, velocity and speed',
    'Acceleration and equations of motion',
    'Graphical analysis of motion',
    'Free fall motion',
    'Relative velocity',
  ]),
  chapter(3, 11, 'Motion in Two Dimensions', [
    'Scalars and vectors',
    'Vector addition and resolution',
    'Projectile motion and trajectory',
    'Circular motion and centripetal acceleration',
    'Relative velocity in two dimensions',
  ]),
  chapter(4, 11, 'Laws of Motion', [
    'Newton first law and inertia',
    'Newton second law and force',
    'Newton third law',
    'Friction and types',
    'Circular motion: dynamics',
  ]),
  chapter(5, 11, 'Work, Energy and Power', [
    'Work done by a force',
    'Kinetic and potential energy',
    'Conservation of energy',
    'Power and efficiency',
    'Collision: elastic and inelastic',
  ]),
  chapter(6, 11, 'System of Particles and Rotational Motion', [
    'Centre of mass',
    'Linear momentum conservation',
    'Moment of force and torque',
    'Angular momentum',
    'Moment of inertia and rotational motion',
    'Rotational kinetic energy',
    'Rolling motion',
  ]),
  chapter(7, 11, 'Gravitation', [
    'Universal law of gravitation',
    'Gravitational field and potential',
    'Acceleration due to gravity',
    'Orbital motion and escape velocity',
    'Satellite motion',
  ]),
  chapter(8, 11, 'Mechanical Properties of Solids', [
    'Stress and strain',
    'Elastic modulus: Young, bulk, shear',
    'Hooke law and applications',
  ]),
  chapter(9, 11, 'Mechanical Properties of Fluids', [
    'Pressure and density',
    'Buoyancy and Archimedes principle',
    'Viscosity and Stokes law',
    'Surface tension and capillarity',
    'Bernoulli theorem',
  ]),
  chapter(10, 11, 'Thermal Properties of Matter', [
    'Temperature and thermometry',
    'Heat and thermal expansion',
    'Thermal conductivity',
    'Phase change and latent heat',
  ]),
  chapter(11, 11, 'Thermodynamics', [
    'Thermal equilibrium and zeroth law',
    'Internal energy',
    'First law of thermodynamics',
    'Heat capacity and specific heat',
    'Thermodynamic processes',
  ]),
  chapter(12, 11, 'Kinetic Theory of Gases', [
    'Ideal gas equation',
    'Gas laws: Boyle, Charles, Gay-Lussac',
    'Mean free path',
    'RMS speed and molecular motion',
    'Kinetic energy and temperature',
  ]),
  chapter(13, 11, 'Oscillations and Simple Harmonic Motion', [
    'Simple harmonic motion',
    'Displacement, velocity and acceleration',
    'Energy in SHM',
    'Spring mass system',
    'Simple pendulum',
    'Damped and forced oscillations',
    'Resonance',
  ]),
  chapter(14, 11, 'Waves', [
    'Wave motion and propagation',
    'Transverse and longitudinal waves',
    'Wavelength, frequency and speed',
    'Equation of wave',
    'Superposition and interference',
    'Standing waves and resonance',
    'Sound waves and Doppler effect',
  ]),
];

const neetPhysicsClass12: CurriculumChapter[] = [
  chapter(1, 12, 'Electric Charges and Fields', [
    'Electric charge and conservation',
    'Coulomb law and principle of superposition',
    'Electric field and field lines',
    'Gauss law and applications',
  ]),
  chapter(2, 12, 'Electrostatic Potential and Capacitance', [
    'Electric potential and potential difference',
    'Potential energy',
    'Equipotential surfaces',
    'Capacitance and capacitors',
    'Dielectrics and Gauss law in dielectrics',
  ]),
  chapter(3, 12, 'Current Electricity', [
    'Electric current and current density',
    'Ohm law and resistivity',
    'Series and parallel resistances',
    'Kirchhoff laws and circuit analysis',
    'Potentiometer and applications',
    'EMF and internal resistance',
  ]),
  chapter(4, 12, 'Moving Charges and Magnetism', [
    'Magnetic field and Lorentz force',
    'Motion of charged particle in magnetic field',
    'Magnetic force on current-carrying conductor',
    'Torque on current loop',
    'Biot-Savart law',
    'Ampere law',
  ]),
  chapter(5, 12, 'Magnetism and Matter', [
    'Bar magnet and magnetic field',
    'Magnetic field of earth',
    'Paramagnetic, diamagnetic and ferromagnetic materials',
  ]),
  chapter(6, 12, 'Electromagnetic Induction', [
    'Faraday law of induction',
    'Lenz law',
    'Induced EMF and current',
    'Self and mutual inductance',
    'Energy stored in magnetic field',
  ]),
  chapter(7, 12, 'Alternating Current', [
    'AC voltage and AC current',
    'RMS value',
    'AC circuits: R, L, C, RC, RL, RLC',
    'Phase relations and impedance',
    'Power in AC circuits',
    'Resonance in AC circuits',
  ]),
  chapter(8, 12, 'Electromagnetic Waves', [
    'Displacement current',
    'Maxwell equations',
    'Electromagnetic wave properties',
    'Speed of electromagnetic waves',
    'EM spectrum',
  ]),
  chapter(9, 12, 'Ray Optics and Optical Instruments', [
    'Reflection and mirrors',
    'Refraction and Snell law',
    'Lenses and lens formula',
    'Optical instruments: microscope, telescope',
    'Defects of vision',
  ]),
  chapter(10, 12, 'Wave Optics', [
    'Huygens principle',
    'Interference and double slit experiment',
    'Diffraction of light',
    'Polarization',
  ]),
  chapter(11, 12, 'Dual Nature of Radiation and Matter', [
    'Photoelectric effect',
    'Einstein photoelectric equation',
    'Matter waves and de Broglie wavelength',
    'Davisson-Germer experiment',
  ]),
  chapter(12, 12, 'Atoms and Nuclei', [
    'Bohr model and energy levels',
    'Hydrogen spectrum',
    'Nuclear composition and structure',
    'Radioactivity and decay',
    'Nuclear reactions and energy',
  ]),
  chapter(13, 12, 'Semiconductor Electronics', [
    'Energy bands in solids',
    'Intrinsic and extrinsic semiconductors',
    'P-N junction and diode',
    'Transistors and gates',
  ]),
];

// NEET-specific Chemistry (NCERT-aligned, simpler than JEE)
const neetChemistryClass11: CurriculumChapter[] = [
  chapter(1, 11, 'Some Basic Concepts of Chemistry', [
    'Matter and its properties',
    'Laws of chemical combination',
    'Atomic and molecular mass',
    'Mole concept and Avogadro number',
    'Molar mass',
    'Stoichiometry and balancing equations',
    'Limiting reagent',
    'Molarity, molality, mole fraction',
  ]),
  chapter(2, 11, 'Structure of Atom', [
    'Subatomic particles',
    'Rutherford model',
    'Bohr model',
    'Quantum mechanical model basics',
    'Quantum numbers and orbitals',
    'Atomic orbitals and shapes',
    'Electron configuration',
  ]),
  chapter(3, 11, 'Classification of Elements and Periodicity', [
    'Modern periodic table',
    'Periodic law',
    'Periodic trends: atomic radius',
    'Ionization enthalpy',
    'Electron gain enthalpy',
    'Electronegativity',
  ]),
  chapter(4, 11, 'Chemical Bonding and Molecular Structure', [
    'Ionic bonding and electronegativity',
    'Covalent bonding',
    'Lewis structures',
    'Octet rule',
    'VSEPR theory',
    'Geometry of molecules',
    'Hybridization',
    'Hydrogen bonding',
  ]),
  chapter(5, 11, 'States of Matter', [
    'Gas laws: Boyle, Charles, Gay-Lussac',
    'Ideal gas equation',
    'Dalton law of partial pressures',
    'Kinetic theory',
    'Liquefaction and critical temperature',
    'Liquid state properties',
    'Solid state basics',
  ]),
  chapter(6, 11, 'Thermodynamics', [
    'System and surroundings',
    'Internal energy',
    'First law of thermodynamics',
    'Work and heat',
    'Enthalpy',
    'Exothermic and endothermic reactions',
    'Hess law',
    'Entropy',
  ]),
  chapter(7, 11, 'Equilibrium', [
    'Dynamic equilibrium',
    'Equilibrium constant',
    'Le Chatelier principle',
    'Effect of concentration, pressure, temperature',
    'Ionic equilibrium',
    'pH and buffer solutions',
    'Solubility product',
  ]),
  chapter(8, 11, 'Redox Reactions', [
    'Oxidation and reduction',
    'Oxidation number',
    'Balancing redox equations',
    'Oxidizing and reducing agents',
  ]),
  chapter(9, 11, 'Hydrogen', [
    'Position in periodic table',
    'Isotopes of hydrogen',
    'Hydrides',
    'Water and hydrogen peroxide',
    'Hydrogen as fuel',
  ]),
  chapter(10, 11, 'The s-Block Elements', [
    'General properties',
    'Alkali metals and compounds',
    'Alkaline earth metals and compounds',
  ]),
  chapter(11, 11, 'The p-Block Elements', [
    'General properties',
    'Group 13: Boron and aluminum',
    'Group 14: Carbon and silicon',
    'Allotropes of carbon',
    'Oxides and halides',
  ]),
  chapter(12, 11, 'Organic Chemistry: Basic Principles and Techniques', [
    'General introduction',
    'Classification of organic compounds',
    'Functional groups',
    'IUPAC nomenclature',
    'Isomerism',
    'Reaction mechanism basics',
  ]),
  chapter(13, 11, 'Hydrocarbons', [
    'Alkanes: structure and properties',
    'Free radical halogenation',
    'Alkenes: structure and nomenclature',
    'Addition reactions',
    'Alkynes',
    'Aromatic hydrocarbons and benzene',
    'Isomerism in aromatic compounds',
    'Petroleum and coal tar',
  ]),
  chapter(14, 11, 'Environmental Chemistry', [
    'Atmosphere composition',
    'Air pollution',
    'Greenhouse effect',
    'Ozone depletion',
    'Water pollution',
    'Soil pollution',
    'Green chemistry',
  ]),
];

const neetChemistryClass12: CurriculumChapter[] = [
  chapter(1, 12, 'Solid State', [
    'Crystalline and amorphous solids',
    'Crystal structure and unit cell',
    'Types of crystals',
    'Packing efficiency',
    'Defects in crystals',
    'X-ray crystallography',
  ]),
  chapter(2, 12, 'Solutions', [
    'Types of solutions',
    'Molarity, molality, mole fraction',
    'Colligative properties',
    'Elevation of boiling point',
    'Depression of freezing point',
    'Osmotic pressure',
  ]),
  chapter(3, 12, 'Electrochemistry', [
    'Galvanic cell',
    'Anode and cathode',
    'Electrode potential',
    'EMF of cell',
    'Batteries and fuel cells',
    'Corrosion',
    'Electrolysis',
    'Faraday laws',
  ]),
  chapter(4, 12, 'Chemical Kinetics', [
    'Rate of reaction',
    'Factors affecting reaction rate',
    'Order of reaction',
    'Rate constant',
    'Integrated rate equations',
    'Half-life',
    'Arrhenius equation',
    'Activation energy',
    'Catalysis',
  ]),
  chapter(5, 12, 'Surface Chemistry', [
    'Adsorption and absorption',
    'Physical and chemical adsorption',
    'Colloids and colloidal solutions',
    'Emulsions and suspension',
    'Coagulation and peptization',
  ]),
  chapter(6, 12, 'General Principles and Processes of Isolation of Elements', [
    'Occurrence of elements',
    'Ores and minerals',
    'Concentration of ore',
    'Extraction methods',
    'Refining of crude metal',
    'Extraction of iron, copper, aluminum',
  ]),
  chapter(7, 12, 'The p-Block Elements', [
    'Group 15: Nitrogen and compounds',
    'Group 16: Oxygen and compounds',
    'Group 17: Halogens',
    'Group 18: Noble gases',
  ]),
  chapter(8, 12, 'Transition and Inner Transition Elements', [
    'General properties of transition metals',
    'Variable oxidation states',
    'Complex formation',
    'Lanthanoids and actinoids',
  ]),
  chapter(9, 12, 'Coordination Compounds', [
    'Ligands and coordination number',
    'Nomenclature',
    'Isomerism',
    'Bonding in complexes',
    'Stability of complexes',
  ]),
  chapter(10, 12, 'Haloalkanes and Haloarenes', [
    'Classification and nomenclature',
    'Preparation',
    'Reactions: substitution and elimination',
    'Nucleophilic aromatic substitution',
  ]),
  chapter(11, 12, 'Alcohols, Phenols and Ethers', [
    'Classification and nomenclature',
    'Preparation of alcohols',
    'Reactions of alcohols',
    'Phenols and reactions',
    'Ethers and Williamson synthesis',
  ]),
  chapter(12, 12, 'Aldehydes, Ketones and Carboxylic Acids', [
    'Nomenclature and classification',
    'Preparation',
    'Physical and chemical properties',
    'Nucleophilic addition reactions',
    'Carboxylic acids and derivatives',
  ]),
  chapter(13, 12, 'Amines', [
    'Classification and nomenclature',
    'Preparation of amines',
    'Physical and chemical properties',
    'Amine salts',
  ]),
  chapter(14, 12, 'Biomolecules', [
    'Carbohydrates: structure and properties',
    'Glucose, fructose, sucrose',
    'Polysaccharides',
    'Proteins: structure and properties',
    'Amino acids and peptide bonds',
    'Enzymes',
    'Vitamins and minerals',
    'Nucleic acids: DNA and RNA',
  ]),
  chapter(15, 12, 'Polymers', [
    'Classification of polymers',
    'Addition and condensation polymerization',
    'Common synthetic polymers',
    'Biopolymers',
    'Plastic degradation and recycling',
  ]),
  chapter(16, 12, 'Chemistry in Everyday Life', [
    'Drugs and their interactions',
    'Chemicals in food',
    'Cleansing agents and detergents',
    'Plasticizers and artificial sweeteners',
  ]),
];

// Mapping of curricula by exam and subject
const getCurriculumChapters = (exam: ExamType, subject: SubjectType): CurriculumChapter[] => {
  if (exam === 'NEET') {
    switch (subject) {
      case 'Physics':
        return [...neetPhysicsClass11, ...neetPhysicsClass12];
      case 'Chemistry':
        return [...neetChemistryClass11, ...neetChemistryClass12];
      case 'Biology':
        return [...biologyClass11, ...biologyClass12];
      case 'Mathematics':
        return []; // Mathematics not in NEET
    }
  } else {
    // JEE_MAINS and JEE_ADVANCED use the same curriculum
    switch (subject) {
      case 'Physics':
        return [...physicsClass11, ...physicsClass12];
      case 'Chemistry':
        return [...chemistryClass11, ...chemistryClass12];
      case 'Mathematics':
        return [...mathematicsClass11, ...mathematicsClass12];
      case 'Biology':
        return []; // Biology not in JEE
    }
  }
};

const buildCurricula = (): CurriculumData[] => {
  const publishers: PublisherType[] = ['NCERT', 'Cengage', 'Arihant', 'Allen', 'PW', 'Unacademy'];
  const curricula: CurriculumData[] = [];

  publishers.forEach((publisher) => {
    // JEE MAINS - Physics, Chemistry, Mathematics
    ['Physics', 'Chemistry', 'Mathematics'].forEach((subject) => {
      curricula.push({
        publisher,
        exam: 'JEE_MAINS',
        subject: subject as SubjectType,
        chapters: getCurriculumChapters('JEE_MAINS', subject as SubjectType),
      });
    });

    // JEE ADVANCED - Physics, Chemistry, Mathematics
    ['Physics', 'Chemistry', 'Mathematics'].forEach((subject) => {
      curricula.push({
        publisher,
        exam: 'JEE_ADVANCED',
        subject: subject as SubjectType,
        chapters: getCurriculumChapters('JEE_ADVANCED', subject as SubjectType),
      });
    });

    // NEET - Physics, Chemistry, Biology
    ['Physics', 'Chemistry', 'Biology'].forEach((subject) => {
      curricula.push({
        publisher,
        exam: 'NEET',
        subject: subject as SubjectType,
        chapters: getCurriculumChapters('NEET', subject as SubjectType),
      });
    });
  });

  return curricula;
};

export const STANDARD_CURRICULA: CurriculumData[] = buildCurricula();

const normalizeExam = (exam: string): ExamType | null => {
  const normalized = exam.trim().toUpperCase();
  if (normalized.includes('NEET')) return 'NEET';
  if (normalized.includes('ADVANCED')) return 'JEE_ADVANCED';
  if (normalized.includes('JEE')) return 'JEE_MAINS';
  return null;
};

const normalizeSubject = (subject: string): SubjectType | null => {
  const normalized = subject.trim().toLowerCase();
  if (normalized === 'physics') return 'Physics';
  if (normalized === 'chemistry') return 'Chemistry';
  if (normalized === 'mathematics' || normalized === 'maths' || normalized === 'math') return 'Mathematics';
  if (normalized === 'biology' || normalized === 'bio') return 'Biology';
  return null;
};

const getCurriculumBase = (publisher: string, exam: string, subject: string): CurriculumData | null => {
  const normalizedExam = normalizeExam(exam);
  const normalizedSubject = normalizeSubject(subject);
  if (!normalizedExam || !normalizedSubject) return null;

  return STANDARD_CURRICULA.find(
    (curriculum) =>
      curriculum.publisher.toLowerCase() === publisher.toLowerCase() &&
      curriculum.exam === normalizedExam &&
      curriculum.subject === normalizedSubject,
  ) || null;
};

export function getExpandedCurriculumData(
  publisher: string,
  exam: string,
  subject: string,
  classLevel?: ClassLevel,
): CurriculumData | null {
  const curriculum = getCurriculumBase(publisher, exam, subject);
  if (!curriculum) return null;

  if (!classLevel) {
    return curriculum;
  }

  return {
    ...curriculum,
    chapters: curriculum.chapters.filter((chapter) => chapter.classLevel === classLevel),
  };
}

export function getCurriculumData(
  publisher: string,
  exam: string,
  subject: string,
  classLevel?: ClassLevel,
): CurriculumData | null {
  return getExpandedCurriculumData(publisher, exam, subject, classLevel);
}

export function getPublishersForExam(exam: string): PublisherType[] {
  return normalizeExam(exam) ? ['NCERT', 'Cengage', 'Arihant', 'Allen', 'PW', 'Unacademy'] : [];
}

export function getSubjectsForPublisherExam(publisher: string, exam: string): SubjectType[] {
  const normalizedExam = normalizeExam(exam);
  if (!normalizedExam) return [];

  if (normalizedExam === 'NEET') {
    return ['Physics', 'Chemistry', 'Biology'];
  }

  return ['Physics', 'Chemistry', 'Mathematics'];
}
